### PR TITLE
added women category component with styles

### PR DESCRIPTION
**Pull request by poojakelkar**
category

- Added women category

### CODE REVIEW

**Review by chanchal-panpaliya — APPROVED** [review]
The code looks clean and easy to understand.  Also, I learned something new. 
${mobile({ flexDirection: "column", padding: "0rem" })}

**Comment by poojakelkar** [comment]
Thanks @chanchal-panpaliya

**Review by shrushti2000 — APPROVED** [review]
Overall everything looks good

**Comment by poojakelkar** [comment]
thanks @shrushti2000

**Pull request merged**
