### PR TITLE
Announce navbar page

### PR DESCRIPTION
**Pull request by poojakelkar**
women

- Added announcement and Navbar

### CODE REVIEW

**Review by darshandamre — APPROVED** [review]
nice design
love the usage of styled components

**Review by hrishikeshmane — APPROVED** [review]
Looks good. You can merge.

**Review by chanchal-panpaliya — COMMENTED** [review]
Your code structure is really impressive.

**Comment by poojakelkar** [comment]
thanks @chanchal-panpaliya   @hrishikeshmane  @darshandamre

**Pull request merged**
