### PR TITLE
Women category-and-login page

### PR DESCRIPTION
**Pull request by poojakelkar**
- Added women's category page to navigate to particular products.
- Added the show password button on the login page.

### CODE REVIEW

**Review by chanchal-panpaliya — APPROVED** [review]
1. code looks clean 
2. proper naming  
3. good file structure.

**Review by SHIKHASINGH1506 — APPROVED** [review]
Major changes in dummy data. I found nothing to be work on. Just check your deployment has failed.

**Comment by poojakelkar** [comment]
@SHIKHASINGH1506  yeah I have created one another for it and created another PR, and the error is for vercel failed

**Review by shrushti2000 — APPROVED** [review]
Just check the deployment part once. Rest all is good.

**Pull request merged**
