### PR TITLE
Women cart

### PR DESCRIPTION
**Pull request by poojakelkar**
cart

### CODE REVIEW

**Review by Rishi05051997 — APPROVED** [review]
Clean Code

**Review by chanchal-panpaliya — CHANGES_REQUESTED** [review]
wrong_code
The code is wrong. You are displaying only static data. Please read the user stories of the e-com project. Update your code before submission.

**Comment by poojakelkar** [comment]
@chanchal-panpaliya yeah, but I will do it after the submission because I am figuring out how to do t so after the submission will add this one. and it navigate to both of the pages using navbar.

**Review by shrushti2000 — APPROVED** [review]
Can be merged

**Comment by poojakelkar** [comment]
thanks @shrushti2000

**Pull request merged**
